version: '3'
services:
  moderate-server:
    build: 
        context: .
        dockerfile: Dockerfile
    image: moderate-server
    container_name: moderate-server
    volumes:
          - '/home/play/projects/myUniverse:/myUniverse' # 数据持久化
          - '/home/play/projects/myUniverse/docs:/docs' # 数据持久化
    ports:
      - 3061:3060
  moderate-redis:
    image: redis
    container_name: moderate-redis
    ports:
      - 6378:6379
    environment:
      - TZ=Asia/Shanghai
  moderate-mongo:
      image: mongo # 引用官网 mongo 镜像
      container_name: moderate-mongo
      restart: always
      volumes:
          - '.docker-volumes/mongo/data:/data/db' # 数据持久化
      environment:
          - MONGO_INITDB_ROOT_USERNAME=admin
          - MONGO_INITDB_ROOT_PASSWORD=123456
          - TZ=Asia/Shanghai # 设置时区
      ports:
          - '27016:27017' # 宿主机可以用 127.0.0.1:27016 即可连接容器中的数据库
      

      