version: '3'
services:
  moderate-server:
    build: 
        context:.
        dockerfile:Dockerfile
    image: moderate-server
    container_name: moderate-server
    ports:
      -3061:3060
  moderate-redis:
    image: redis
    container_name: moderate-redis
    ports:
      -6378:6379
    environment:
      - TZ=Asia/Shanghai
      